[package]
name = "allvu"
version = "0.1.0"
edition = "2021"

[dependencies]
aggligator = "0.9.5"
aggligator-transport-tcp = "0.2.0"
anyhow = "1.0.97"
serde = { version = "1.0.219", features = ["derive"] }
text_io = "0.1.13"
tokio = { version = "1.44.1", features = ["full"] }
toml = "0.8.20"
